param(
    [ValidateSet('HighCpuUsage', 'DiskSpaceHigh', 'MemoryPressure', 'ServiceDown', 'JvmHeapHigh')]
    [string]$AlertName = 'HighCpuUsage',
    [ValidateSet('critical', 'warning', 'info')]
    [string]$Severity = 'critical',
    [string]$Instance = '192.168.88.137',
    [string]$Service = 'elasticsearch',
    [string]$BackendUrl = 'http://localhost:8080'
)

$summary = switch ($AlertName) {
    'HighCpuUsage' { 'CPU usage above 90% for 5 minutes' }
    'DiskSpaceHigh' { 'Disk usage above 85% on root filesystem' }
    'MemoryPressure' { 'Memory usage above 88% for 10 minutes' }
    'ServiceDown' { 'Target service is unreachable' }
    'JvmHeapHigh' { 'JVM heap usage above 90%' }
    default { 'Test alert generated by inject-test-alert.ps1' }
}

$body = @{
    receiver = 'aiops-webhook'
    status = 'firing'
    alerts = @(
        @{
            status = 'firing'
            labels = @{
                alertname = $AlertName
                severity = $Severity
                instance = $Instance
                job = 'node-exporter'
                service = $Service
            }
            annotations = @{
                summary = $summary
                description = "Injected test alert for $AlertName on $Instance"
            }
            startsAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffZ')
            fingerprint = "$AlertName-$Instance-$(Get-Date -Format 'yyyyMMddHHmmss')"
        }
    )
} | ConvertTo-Json -Depth 6

$result = Invoke-RestMethod -Uri "$BackendUrl/api/alerts/webhook" -Method POST -ContentType 'application/json' -Body $body
Write-Host "Webhook success=$($result.success) saved=$($result.saved) received=$($result.received)"
Write-Host 'MQ will auto-create ticket and run default-model diagnosis in a few seconds.'
